services:
  postgres:
    image: postgres:16-alpine
    container_name: sirer_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sirer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - sirer_pgdata:/var/lib/postgresql/data

volumes:
  sirer_pgdata:
